src/const/theme.js
I want two nord themes, bright and dark, so I made it with reference to [https://www.nordtheme.com/docs/colors-and-palettes](https://www.nordtheme.com/docs/colors-and-palettes)
=> Add nord theme.

src/app.js
=> [FIX] TypeError: core.warn is not a function

src/templates/profile-details-card.js
=> [profile-details] Fix chart x axis tick

src/cards/most-commit-lauguage-card.js, src/cards/profile-details-card.js, src/cards/repos-per-language-card.js, src/cards/stats-card.js
See title.
I felt that some of the wording used in the cards was awkward, or that some added capitalisation in places could improve the way the cards look. Originally I was going to simply maintain a fork, but integrating that fork with GitHub actions became troublesome, so instead I'm (attempting to) contribute to the main repo.
I wasn't sure whether to open an issue or not. Let me know if there's a preference for PRs to have issues attached.
**UPDATE**
Closes #17
=> Improve wording in summary cards

src/app.js, src/cards/productive-time-card.js, src/github-api/productive-time.js, src/templates/card.js, src/templates/productive-time-card.js
=> Add productive time card

src/templates/card.js
To make card more fit to github
=> Change card corner-radius & stroke-width

src/cards/productive-time-card.js, src/github-api/productive-time.js, src/github-api/profile-details.js, tests/github-api/profile-details.test.js
=> Fix github commit time api

api/cards/most-commit-language.js, api/cards/productive-time.js, api/cards/profile-details.js, api/cards/repos-per-language.js, api/cards/stats.js
=> :sparkles: Added Default case for theme parameter #53

.gitignore, api/pages/demo.html
=> Modify demo web

README.md
Made some grammatic correction
=> Correction 

README.md, docs/README.zh-tw.md
=> fix GITHUB_TOKEN secret name

src/const/theme.ts
New color themes :
- radical (https://github.com/vn7n24fzkq/github-profile-summary-cards/issues/66 )
- gruvbox
- tokyonight
- cobalt
- dark
=> new color themes

package-lock.json, package.json
=> chore: bump axios from 0.21.2 to 0.21.3

README.md, src/const/theme.ts
Add [Zenburn](https://kippura.org/zenburnpage/) theme, plus some opportunistic improvements in the README :nerd_face:
=> feat(themes): add Zenburn

.github/workflows/github-action.yml, README.md
Update foresight CI and fix badges
=> chore: foresight configure

src/cards/productive-time-card.ts, src/templates/productive-time-card.ts
=> Fixed decimal UTC time bug

README.md, src/const/theme.ts, tests/const/theme.test.ts
I tried to resolove for feature request #73.
For the color scheme, I used the following site as a reference.
https://github.com/anuraghazra/github-readme-stats/blob/9eb0c3cbb40d551b93536c45100994d4c83b8c04/themes/index.js#L15
=> feat: Add transparent theme

README.md
To fix this problem #129 
I only edited source code on README.md
=> docs: added content-write permission

package-lock.json
Below comment apper at test running.
I want to solve it.
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
ref: https://caniuse.com/
Run at node 16.18.1 that is same version as GitHub Actions node 16.x
```
npm install
npx browserslist@latest --update-db
```
=> chore: Update browserslist 🔼

vercel.json
=> fix: add default build folder

.github/workflows/publish-wiki.yml, wiki/Home.md
To automatic publish the wiki and sync the code with documents.
=> Feat: add wiki action

package.json
Define the node version on the project explicitly.
docs: https://vercel.com/docs/functions/runtimes/node-js/node-js-versions#version-overrides-in-package.json
=> build: update node version to 20.x
